### ISSUE TITLE
能不能提供全部的架构

### ISSUE THREAD

**Issue by mosentest** [yutianzuo/android-curl#1]
能不能提供全部的架构

**Comment by yutianzuo** [comment]
现在主流的做法是只用v7a架构，这样兼容性最好，你的app中只保留v7a即可，64位的都带上会增大很多包体积。

**Comment by yutianzuo** [comment]
已经加入arm64版本so，测试case通过。

**Comment by mosentest** [comment]
能不能指点下我啊

**Comment by mosentest** [comment]
用你脚本，我编译出来没看到.a文件

**Comment by yutianzuo** [comment]
编译curl需要先编译openssl， 否则无法进行https请求。
openssl编译过程比较复杂， 一句两句说不明白，建议你直接用编译好的a文件。
